import QtQuick 2.15
import QtQuick.Layouts 1.15
import "." as CyberComponents

/*
 * Network & Wi-Fi Studio Glass Card Module for SDDM
 * Reads live hostname, Wi-Fi SSID, and IP address diagnostics generated by sddm-telemetry-update service.
 */
CyberComponents.GlassCard {
    id: networkCard
    width: 372
    // Height follows the content. Hardcoded heights matched the rows exactly,
    // so the last row sat on the border and clipped as soon as any value
    // wrapped or a font metric differed.
    implicitHeight: content.implicitHeight + 36
    height: implicitHeight

    property string fontName: "JetBrainsMono Nerd Font"
    property string activeHostname: "workstation"

    ColumnLayout {
        id: content
        anchors.left: parent.left
        anchors.right: parent.right
        anchors.top: parent.top
        anchors.margins: 18
        spacing: 12

        // Section Title Header
        Text {
            text: "> NETWORK & WI-FI"
            font.family: networkCard.fontName
            font.pointSize: 11
            font.weight: Font.Bold
            font.letterSpacing: 1.2
            color: "#38BDF8" // Vibrant Cyan
            Layout.bottomMargin: 4
        }

        component NetworkRow: RowLayout {
            property string icon: ""
            property string iconColor: "#2DD4BF"
            property string label: ""
            property string val: ""
            spacing: 12
            Layout.fillWidth: true
            
            Text {
                text: icon
                font.family: networkCard.fontName
                font.pointSize: 13
                color: iconColor
                Layout.preferredWidth: 22
            }
            Text {
                text: label
                font.family: networkCard.fontName
                font.pointSize: 11
                color: "#94A3B8"
                Layout.preferredWidth: 90
            }
            Text {
                text: val
                font.family: networkCard.fontName
                font.pointSize: 11
                font.weight: Font.Medium
                color: "#F8FAFC"
                Layout.fillWidth: true
                elide: Text.ElideRight
            }
        }

        NetworkRow { icon: "󰇄"; iconColor: "#38BDF8"; label: "Hostname"; val: typeof config !== "undefined" && config.hostName ? config.hostName : networkCard.activeHostname }
        NetworkRow { icon: ""; iconColor: "#2DD4BF"; label: "Wi-Fi"; val: typeof config !== "undefined" && config.wifiEssid ? config.wifiEssid : "Ethernet / Wired" }
        NetworkRow { icon: "󰩠"; iconColor: "#818CF8"; label: "Local IP"; val: typeof config !== "undefined" && config.localIP ? config.localIP : "Detecting Link..." }
        NetworkRow { icon: "󰩠"; iconColor: "#A78BFA"; label: "Public IP"; val: typeof config !== "undefined" && config.publicIP ? config.publicIP : "Protected Link" }
        // Was hardcoded to "Active Gigabit Link" whatever the real link was --
        // wrong on every Wi-Fi machine, including this one. linkStatus is emitted
        // by sddm-telemetry-update from the actual default route.
        NetworkRow { icon: "󰇚"; iconColor: "#22C55E"; label: "Status"
                     val: typeof config !== "undefined" && config.linkStatus ? config.linkStatus : "Unknown" }

        Item { Layout.fillHeight: true }
    }
}
